---

- hosts: all
  become: true
  pre_tasks:
  
  - name: Update All Systems
    tags: always
    apt:
      update_cache: true
      upgrade: safe
      autoremove: true
      autoclean: true

- host: all
  become: true
  roles:
    - base
    